# These are supported funding model platforms

github: [ANAMIZED]
custom:
  - "https://donate.stripe.com/00w5kE3wOg5L8Jn2F243S00"
  - "https://buy.stripe.com/7sY8wQ5EWf1H3p3bby43S01"
  - "https://buy.stripe.com/bJecN63wObPv6Bf7Zm43S02"
